### ISSUE TITLE
Support 'all' from the -d option

### ISSUE THREAD

**Issue by jlstack** [ibmjstart/bluemix-cloudant-sync#2]
consider supporting 'all' from the -d option...or alternately supporting an option like -a for it or --all

**Comment by jlstack** [comment]
running "cf cloudant-replicate -d all" should now work

**Comment by lmsurpre** [comment]
just don't name your database "all".  wonder if it should just be a
different flag like "--all-db".  do we accept "all" from the interactive
prompt as well, or just the numeric index?

Lee Surprenant
IBM Emerging Technologies | jStart Team
lmsurpre@us.ibm.com | (919) 543-8919

**Comment by jlstack** [comment]
To answer your question about the "all" from the interactive prompt, if more than one database is found, an option is printed that says "sync all databases". This option appears in the list of databases and can be selected just like any of the other databases from the prompt.
