### ISSUE TITLE
Handle both 201 and 202 response codes as success

### ISSUE THREAD

**Issue by lmsurpre** [ibmjstart/bluemix-cloudant-sync#5]
During a demo we saw a 202 response code printed out as a "Failure". I did see a fix for that yet and so I wanted to open an issue so we don't forget about it.

**Comment by jlstack** [comment]
I accepted the 202 response when creating documents and databases. I do not believe that either of those are possible when doing things like creating/deleting cookies and modifying permissions. At least I did not see anywhere in the documentation where they were possible. They were only explicitly stated for creating documents and databases.
