### ISSUE TITLE
Wrong version number in the plugin metadata

### ISSUE THREAD

**Issue by lmsurpre** [ibmjstart/bluemix-cloudant-sync#6]
> cf install-plugin /Users/lmsurpre/bin/bc-replicator_0.1.2_osx 

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin /Users/lmsurpre/bin/bc-replicator_0.1.2_osx? (y or n)> y

Installing plugin /Users/lmsurpre/bin/bc-replicator_0.1.2_osx...
OK
Plugin bluemix-cloudant-replicator v1.0.0 successfully installed.

**Comment by jlstack** [comment]
This issue was resolved in the 0.1.3 release
