### ISSUE TITLE
Usage detail should specify that -d takes a comma-separated list

### ISSUE THREAD

**Issue by lmsurpre** [ibmjstart/bluemix-cloudant-sync#7]
> cf help cloudant-replicate
> NAME:
>    cloudant-replicate - configures replication across Cloudant databases in multiple Bluemix regions

USAGE:
   cf cloudant-replicate [-a APP] [-d DATABASE] [-p PASSWORD] [--all-dbs] [--create]

OPTIONS:
   -a              App
   -d              Database
   -p              Password
   --all-dbs       Select all databases
   --create        Create non-existing databases

**Comment by jlstack** [comment]
This issue was resolved in the 0.1.3 release
